ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: "'trackmyasset'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py", line 42, in index
    return render(request, 'index.html', context)
  File "C:\Program Files\Python37\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Program Files\Python37\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Program Files\Python37\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Program Files\Python37\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 528, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 13: ''trackmyasset'', expected 'endblock'. Did you forget to register or load this tag?
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: "'trackmyasset'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py", line 42, in index
    return render(request, 'index.html', context)
  File "C:\Program Files\Python37\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Program Files\Python37\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Program Files\Python37\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Program Files\Python37\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 528, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 13: ''trackmyasset'', expected 'endblock'. Did you forget to register or load this tag?
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py", line 44, in index
    return render(request, 'index.html', context)
  File "C:\Program Files\Python37\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Program Files\Python37\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Program Files\Python37\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Program Files\Python37\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Program Files\Python37\lib\site-packages\django\templatetags\static.py", line 159, in do_static
    return StaticNode.handle_token(parser, token)
  File "C:\Program Files\Python37\lib\site-packages\django\templatetags\static.py", line 133, in handle_token
    path = parser.compile_filter(bits[1])
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 663, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '/gps.jpeg'' from 'images/gps.jpeg''
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
WARNING:django.request:Not Found: /static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /static/images/gps.jpeg
WARNING:django.request:Not Found: /static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /static/images/gps.jpeg
WARNING:django.request:Not Found: /static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /static/images/gps.jpeg
WARNING:django.request:Not Found: /static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /static/images/gps.jpeg
WARNING:django.request:Not Found: /static/images/gps.jpeg
WARNING:django.request:Not Found: /static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /static/images/gps.jpeg
WARNING:django.request:Not Found: /static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /static/images/gps.jpeg
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\urls.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/trackmyasset/static/images/gps.jpeg
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: "'trackmyasset'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py", line 44, in index
    return render(request, 'index.html', context)
  File "C:\Program Files\Python37\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Program Files\Python37\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Program Files\Python37\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Program Files\Python37\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 528, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 11: ''trackmyasset'', expected 'endblock'. Did you forget to register or load this tag?
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: './static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py", line 44, in index
    return render(request, 'index.html', context)
  File "C:\Program Files\Python37\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Program Files\Python37\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Program Files\Python37\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Program Files\Python37\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 528, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 11: './static', expected 'endblock'. Did you forget to register or load this tag?
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
WARNING:django.request:Not Found: /trackmyasset/trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/trackmyasset/static/images/gps.jpeg
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
WARNING:django.request:Not Found: /trackmyasset/trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/trackmyasset/static/images/gps.jpeg
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
WARNING:django.request:Not Found: /trackmyasset/trackmyasset/static/images/gps.jpeg
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
WARNING:django.request:Not Found: /trackmyasset/trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/trackmyasset/static/images/gps.jpeg
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader_tags.py", line 104, in find_template
    template_name, skip=history,
  File "C:\Program Files\Python37\lib\site-packages\django\template\engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py", line 44, in index
    return render(request, 'index.html', context)
  File "C:\Program Files\Python37\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Program Files\Python37\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Program Files\Python37\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader_tags.py", line 104, in find_template
    template_name, skip=history,
  File "C:\Program Files\Python37\lib\site-packages\django\template\engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py", line 44, in index
    return render(request, 'index.html', context)
  File "C:\Program Files\Python37\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Program Files\Python37\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Program Files\Python37\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING:django.request:Bad Request: /
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\urls.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\urls.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\urls.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\urls.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\urls.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /admin/trackmyasset/static/admin/css/base.css
WARNING:django.request:Not Found: /admin/trackmyasset/static/admin/css/dashboard.css
WARNING:django.request:Not Found: /admin/trackmyasset/static/admin/css/responsive.css
WARNING:django.request:Not Found: /admin/trackmyasset/static/admin/css/base.css
WARNING:django.request:Not Found: /admin/trackmyasset/static/admin/css/responsive.css
WARNING:django.request:Not Found: /admin/trackmyasset/static/admin/css/dashboard.css
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trip/trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trip/trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trip/trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /assets/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/assets/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/assets/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/assets/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/assets/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/assets/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/assets/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/assets/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/assets/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/assets/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/assets/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/assets/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/assets/gps.jpeg
WARNING:django.request:Not Found: /static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/assets/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/assets/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/assets/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/assets/gps.jpeg
WARNING:django.request:Not Found: /static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/assets/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/assets/gps.jpeg
WARNING:django.request:Not Found: /static/images/gps.jpeg
WARNING:django.request:Not Found: /static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/assets/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/assets/gps.jpeg
WARNING:django.request:Not Found: /static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/assets/gps.jpeg
WARNING:django.request:Not Found: /static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
WARNING:django.request:Not Found: /trackmyasset/static/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/TrackMyAsset.png
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /favicon.ico
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py", line 44, in index
    return render(request, 'index.html', context)
  File "C:\Program Files\Python37\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Program Files\Python37\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader_tags.py", line 104, in find_template
    template_name, skip=history,
  File "C:\Program Files\Python37\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 534, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 11: 'static'. Did you forget to register or load this tag?
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /account/register
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py", line 8, in register
    return render(request, 'register.html', {'register_form'})
  File "C:\Program Files\Python37\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Program Files\Python37\lib\site-packages\django\template\backends\django.py", line 59, in render
    context = make_context(context, request, autoescape=self.backend.engine.autoescape)
  File "C:\Program Files\Python37\lib\site-packages\django\template\context.py", line 270, in make_context
    raise TypeError('context must be a dict rather than %s.' % context.__class__.__name__)
TypeError: context must be a dict rather than set.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /account/register
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py", line 12, in register
    return redirect('trips')
  File "C:\Program Files\Python37\lib\site-packages\django\shortcuts.py", line 58, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "C:\Program Files\Python37\lib\site-packages\django\shortcuts.py", line 148, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "C:\Program Files\Python37\lib\site-packages\django\urls\base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "C:\Program Files\Python37\lib\site-packages\django\urls\resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'trips' not found. 'trips' is not a valid view function or pattern name.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\forms.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\forms.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\urls.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\urls.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\urls.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\urls.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\urls.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\urls.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\urls.py changed, reloading.
ERROR:django.request:Internal Server Error: /account/login
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Program Files\Python37\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "C:\Program Files\Python37\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Program Files\Python37\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\urls.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\urls.py changed, reloading.
WARNING:django.request:Not Found: /accounts/profile/
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
WARNING:django.request:Not Found: /accounts/register/
WARNING:django.request:Not Found: /accounts/login/
WARNING:django.request:Not Found: /accounts/
WARNING:django.request:Not Found: /accounts/login
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\urls.py changed, reloading.
WARNING:django.request:Not Found: /accounts/login
WARNING:django.request:Not Found: /accounts/register
WARNING:django.request:Not Found: /accounts/register
WARNING:django.request:Not Found: /accounts/register
WARNING:django.request:Not Found: /accounts/register
WARNING:django.request:Not Found: /accounts/register/
WARNING:django.request:Not Found: /accounts/
WARNING:django.request:Not Found: /accounts/logout
WARNING:django.request:Not Found: /accounts/logout
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\urls.py changed, reloading.
WARNING:django.request:Not Found: /accounts/logout
WARNING:django.request:Not Found: /accounts/logout
WARNING:django.request:Not Found: /accounts/logout
WARNING:django.request:Not Found: /accounts/logout
WARNING:django.request:Not Found: /accounts/login
WARNING:django.request:Not Found: /accounts/login
WARNING:django.request:Not Found: /accounts/login
WARNING:django.request:Not Found: /accounts/login
WARNING:django.request:Not Found: /accounts/login
WARNING:django.request:Not Found: /accounts/logout
WARNING:django.request:Not Found: /accounts/logout
WARNING:django.request:Not Found: /accounts/logout
WARNING:django.request:Not Found: /accounts/login
WARNING:django.request:Not Found: /accounts/login
WARNING:django.request:Not Found: /accounts/login
WARNING:django.request:Not Found: /accounts/login
WARNING:django.request:Not Found: /accounts/login
WARNING:django.request:Not Found: /accounts/login
WARNING:django.request:Not Found: /accounts/login
WARNING:django.request:Not Found: /accounts/login/
WARNING:django.request:Not Found: /accounts/logout
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\urls.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\urls.py changed, reloading.
ERROR:django.request:Internal Server Error: /account/logout
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Program Files\Python37\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "C:\Program Files\Python37\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Program Files\Python37\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
ERROR:django.request:Internal Server Error: /account/logout
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Program Files\Python37\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "C:\Program Files\Python37\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Program Files\Python37\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
ERROR:django.request:Internal Server Error: /account/logout
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Program Files\Python37\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "C:\Program Files\Python37\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Program Files\Python37\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
ERROR:django.request:Internal Server Error: /account/logout
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Program Files\Python37\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "C:\Program Files\Python37\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Program Files\Python37\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\urls.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\urls.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\urls.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\urls.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\urls.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\users_app\urls.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
WARNING:django.request:Not Found: /accounts/login/
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
WARNING:django.security.csrf:Forbidden (CSRF cookie not set.): /admin/login/
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /trip/
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\Python37\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py", line 29, in trip
    return redirect(request, 'trip.html', {'all_Trips': all_Trips})
  File "C:\Program Files\Python37\lib\site-packages\django\shortcuts.py", line 58, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "C:\Program Files\Python37\lib\site-packages\django\shortcuts.py", line 148, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "C:\Program Files\Python37\lib\site-packages\django\urls\base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "C:\Program Files\Python37\lib\site-packages\django\urls\resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '<WSGIRequest: GET '/trip/'>' not found. '<WSGIRequest: GET '/trip/'>' is not a valid view function or pattern name.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Program Files\Python37\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader_tags.py", line 104, in find_template
    template_name, skip=history,
  File "C:\Program Files\Python37\lib\site-packages\django\template\engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py", line 43, in index
    return render(request, 'index.html', context)
  File "C:\Program Files\Python37\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Program Files\Python37\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Program Files\Python37\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /trip/
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\Python37\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py", line 30, in trip
    t = loader.get_template('trips_app/trip.html')
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: trips_app/trip.html
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /trip/
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\Python37\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py", line 30, in trip
    t = loader.get_templates('trips_app/trip.html')
AttributeError: module 'django.template.loader' has no attribute 'get_templates'
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /trip/
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\Python37\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py", line 30, in trip
    t = loader.get_template('trips_app/trip.html')
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: trips_app/trip.html
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /trip/
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\Python37\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py", line 30, in trip
    t = loader.get_template('trips_app/trip.html')
  File "C:\Program Files\Python37\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: trips_app/trip.html
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\urls.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\urls.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\urls.py changed, reloading.
WARNING:django.security.csrf:Forbidden (CSRF token missing or incorrect.): /account/login
WARNING:django.security.csrf:Forbidden (CSRF token missing or incorrect.): /account/login
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\urls.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
WARNING:django.security.csrf:Forbidden (CSRF token missing or incorrect.): /account/login
ERROR:django.request:Internal Server Error: /trip/delete/5
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\Python37\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py", line 60, in delete_task
    if task.manage == request.user:
AttributeError: 'Trips' object has no attribute 'manage'
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trips_app\views.py changed, reloading.
WARNING:django.security.csrf:Forbidden (CSRF token missing or incorrect.): /account/login
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /TrackMyAsset-project/static/images/gps.jpeg
WARNING:django.request:Not Found: /TrackMyAsset-project/static/images/gps.jpeg
WARNING:django.request:Not Found: /TrackMyAsset-project/static/images/gps.jpeg
WARNING:django.request:Not Found: /TrackMyAsset-project/static/images/gps.jpeg
WARNING:django.request:Not Found: /TrackMyAsset-project/static/images/gps.jpeg
WARNING:django.request:Not Found: /TrackMyAsset-project/static/images/gps.jpeg
WARNING:django.request:Not Found: /TrackMyAsset-project/static/images/gps.jpeg
WARNING:django.request:Not Found: /TrackMyAsset-project/static/images/gps.jpeg
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
WARNING:django.request:Not Found: /TrackMyAsset-project/trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /TrackMyAsset-project/trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /TrackMyAsset-project/trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /TrackMyAsset-project/trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /TrackMyAsset-project/trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /TrackMyAsset-project/trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /TrackMyAsset-project/trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /TrackMyAsset-project/trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /TrackMyAsset-project/trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /TrackMyAsset-project/trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpeg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpg
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpg
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpg
INFO:django.utils.autoreload:C:\Users\jimah\Desktop\TrackMyAsset-Django\TrackMyAsset-project\trackmyasset\trackmyasset\settings.py changed, reloading.
WARNING:django.request:Not Found: /trackmyasset/static/images/gps.jpg
